### ISSUE TITLE
Issue System.TypeLoadException: Method 'WriteTo' in type .. does not have an implementation

### ISSUE THREAD

**Issue by chuongmep** [jowsy/bim-net-interactive#2]
I saw a issue when try debug from my side, so it is same issue with your side ? I guess have some addin conflict here : 

https://github.com/jowsy/bim-net-interactive/blob/dce8b0031339a30092095c26fd3ce3e43eb9e01e/src/Jowsy.Revit.KernelAddin/Core/RevitKernel.cs#L105

And here : 
https://github.com/jowsy/bim-net-interactive/blob/b11e75b78df998474d772f1b71a89a67c7a00cef/src/Jowsy.Revit.KernelAddin/App.cs#L46-L51
System : Windows 11 
Revit Version : 2024 
Visual Studio Code : Latest 
Extenstion Visual Code : Beta Latest
Details : 
System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Interactive.Formatting.Formatter' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Interactive.Formatting.HtmlFormatter' threw an exception. ---> System.TypeLoadException: Method 'WriteTo' in type 'Microsoft.DotNet.Interactive.Formatting.PocketView' from assembly 'Microsoft.DotNet.Interactive.Formatting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.DotNet.Interactive.Formatting.HtmlFormatter..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Interactive.Formatting.Formatter.ResetToDefault()
   at Microsoft.DotNet.Interactive.Formatting.Formatter..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Interactive.Formatting.Formatter.ToDisplayString(Object obj, String mimeType)
   at Jowsy.Revit.KernelAddin.Core.RevitKernel.CreateSingleFromObject(Object value, String mimeType)
   at Jowsy.Revit.KernelAddin.Core.RevitKernel.<>c.<HandleAsync>b__4_0(KeyValuePair`2 v)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Jowsy.Revit.KernelAddin.Core.RevitKernel.HandleAsync(RequestValueInfos command, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.Kernel.<>c__DisplayClass82_0`1.<SetHandler>b__0(KernelCommand _, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.Commands.KernelCommand.InvokeAsync(KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.Kernel.<HandleAsync>d__56.MoveNext()

**Comment by jowsy** [comment]
Ok, this is probably a dll conflict with the BIM 360 issue addin (System.Memory.Encodings as I recall it). For the time being, I haven't found a solution other than disabling the addin.

**Comment by chuongmep** [comment]
@jowsy  my computer doesn't have `BIM 360 issue addin`. I think it come from another add-in also. 
But I `System.Memory.Encodings` is good catch for me to find it. Thank you.

**Comment by jowsy** [comment]
I have gone through this again and find that it conflicts with Autodesk Interoperability Tools.
![explorer_nDuiuFnCZ9](https://github.com/jowsy/bim-net-interactive/assets/78738216/f5e79613-e809-4618-b504-c3f76e371333)

**Comment by chuongmep** [comment]
Hi @jowsy, thanks you for your message, I will try with that

**Comment by chuongmep** [comment]
After disable add-in `Autodesk Interoperability Tools`, I'm still facing with same problem, may be we need find solution to fix instead disable addin
